### ISSUE TITLE
Run Pomelo.EntityFrameworkCore.MySql tests

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/MySqlConnector#36]
See PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#40 for background.

Modify `Pomelo.EntityFrameworkCore.MySql.Tests` to use `MySqlConnector` and see if all the tests pass; create issues for test failures.

**Comment by bgrainger** [comment]
Looks like the libraries won't be compatible due to "non standard" properties added in `Pomelo.Data.MySql` such as [`MySqlConnection.Reader`](https://github.com/PomeloFoundation/Pomelo.Data.MySql/blob/aaf215852d594d09cf6518e50392b596b46a9f18/src/Pomelo.Data.MySql/Connection.cs#L85).

**Comment by bgrainger** [comment]
[MySqlTypeMapping](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlTypeMapping.cs) uses `MySqlDbType`, which has not been ported to this library.

**Comment by caleblloyd** [comment]
@bgrainger I've opened a PR to switch Pomelo's ADO.NET driver to this repository: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/44

If you could do a code review in the PR I would really appreciate it!

Also, it's currently blocked on #42, I've got pr #43 open that fixes

**Comment by bgrainger** [comment]
The Pomelo PR is tracking the status of this work.
