### ISSUE TITLE
ipv6 issues

### ISSUE THREAD

**Issue by tanthorjen** [bgrainger/MySqlConnector#37]
Hi,

If the client has ipv6 but the mysql machine has ipv4, the socket connection fails with "Address System.Net.Sockets.SocketException: An address incompatible with the requested protocol was used error".

I've solved the issue, and it's a simple fix:

Replace line in MySqlSession.cs:
                        socket = new Socket(SocketType.Stream, ProtocolType.Tcp);

With:
                        socket = new Socket(ipAddress.AddressFamily, SocketType.Stream, ProtocolType.Tcp);

**Comment by bgrainger** [comment]
Thanks for the fix!

I wasn't able to reproduce the problem, but the code looks reasonable so I shipped alpha 14 with your patch: https://www.nuget.org/packages/MySqlConnector/0.1.0-alpha14

**Comment by tanthorjen** [comment]
Thanks! Now all we need is a keep alive feature. :)
