### ISSUE TITLE
Implement connection pooling.

### ISSUE THREAD

**Issue by OzieGamma** [bgrainger/MySqlConnector#38]
Hi,

I tried your connector out. It worked in a small demo App ("select name from users").

When I launched a load test (I wanted to test .NET Core performance on Swisscom cloud), It ended up crashing quite often with "Not more connections available".

Maybe I am doing something wrong, here is my code:
```csharp
    public interface IDb
    {
        Task<IList<string>> GetUserNames();
    }

    public class Db : IDb
    {
        public string ConnectionString { get; private set; }

        public Db(string connectionString)
        {
            this.ConnectionString = connectionString;
        }

        public async Task<IList<string>> GetUserNames()
        {
            using (IDbConnection connection = new MySqlConnection(ConnectionString))
            {
                var results = await connection.QueryAsync<string>("select Name from Users");
                return results.AsList();
            }
        }
    }
```

**Comment by bgrainger** [comment]
Although I have used connection pooling with this library, it hasn't been stress-tested yet, so there may be a bug.

What is the full connection string (without User ID and Password)? Approximately how many connections are you opening simultaneously?

**Comment by OzieGamma** [comment]
```csharp
            dynamic vcap_services = JsonConvert.DeserializeObject(Configuration["VCAP_SERVICES"]);

            var server = vcap_services.mariadb[0].credentials.host;
            var port = vcap_services.mariadb[0].credentials.port;
            var database = vcap_services.mariadb[0].credentials.database;
            var username = vcap_services.mariadb[0].credentials.username;
            var password = vcap_services.mariadb[0].credentials.password;
            var connectionString =
                $"Server = {server}; Port = {port}; Database = {database}; Uid = {username};Pwd = {password};";
```

I guess it creates one per Http Request?

Isn't the library supposed to handle that? 

Or do I need to specify the max number of connections in the connection string?

**Comment by bgrainger** [comment]
The library should handle that just fine. Can you paste in the complete exception message and full call stack you're getting when it fails?

**Comment by OzieGamma** [comment]
Sure, I'll do that tomorrow!

**Comment by caleblloyd** [comment]
There is definitely an issue with the connection pool, I'm hitting in in performance tests from #55 

I'm working up a separate PR with a fix right now

**Comment by OzieGamma** [comment]
Sorry for never answering this. I moved to use Postgres (use a different provider).

**Comment by bgrainger** [comment]
A connection pooling PR has been merged; closing this issue due to lack of steps to repro.
