### ISSUE TITLE
Implement "Connect Timeout" connection string setting

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/MySqlConnector#57]
Add `MySqlConnectionStringBuilder.ConnectionTimeout` setting (aliases: Connect Timeout, Connection Timeout, ConnectionTimeout). According to https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html it has a default value of 15.

A "Timeout expired" `MySqlException` should be thrown when:
* the connection pool isn't full, but connecting to the server takes longer than the timeout
* the connection pool is full and a connection isn't returned in time (see #56)

**Comment by caleblloyd** [comment]
Yup, I think this is the problem with tests hanging.  I'm working up a fix now.

Connections to invalid servers never time out, so pool can never clear when the test is disposed.

Will work up a separate PR for this issue.

**Comment by bgrainger** [comment]
@caleblloyd I have some WIP at https://github.com/bgrainger/MySqlConnector/tree/test

Also working on rebuilding #56 in stages to fix issues one-at-a-time without regressing the tests.

**Comment by bgrainger** [comment]
> the connection pool is full and a connection isn't returned in time

This still needs to be implemented.

**Comment by caleblloyd** [comment]
The majority of this was implemented in https://github.com/bgrainger/MySqlConnector/commit/d65a3aee2356563b9fce93a1d049714f742159b5

I am opening a PR to fix up the `ConnectionTimeout` method in `MySqlConnection`
