### ISSUE TITLE
Fix 'ClearPool' behavior

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/MySqlConnector#58]
According to [MySQL Documentation](https://dev.mysql.com/doc/dev/connector-net/html/M_MySql_Data_MySqlClient_MySqlConnection_ClearPool.htm):

> ClearPool clears the connection pool that is associated with the connection. If additional connections associated with connection are in use at the time of the call, they are marked appropriately and are discarded (instead of being returned to the pool) when Close is called on them.

Connections that are active when `ClearPool` is called should be flagged to be cleared as soon as they are returned.

**Comment by caleblloyd** [comment]
I've implemented a fix and corresponding test for this in https://github.com/caleblloyd/MySqlConnector/commit/fcc8ddf4f5bd8805d1b0f703f854d5b60dafe071

I'm going to wait for `sync-io` to merge to master before I open a PR to avoid merge conflicts.
