### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/MySqlConnector#6]
Run the tests on as many .NET Core platforms as possible.

**Comment by greghroberts** [comment]
This is great! Was thinking of doing this myself, but would love to help contribute.  Do you have any up for grabs issues like this one you want help on?  Are you basing any of this on existing projects like https://github.com/mysqljs/mysql ?

**Comment by bgrainger** [comment]
This is probably the most "up for grabs" issue right now. I had Travis and Appveyor builds running previously, but they seemed to keep failing due to environmental issues (i.e., getting the latest .NET Core RC actually installed and working correctly on the CI box). If you have experience with getting a .NET Core xunit test library running under public CI, I'd love help!

This project is mostly based on my experience building a [SQLite ADO.NET provider](https://github.com/Faithlife/System.Data.SQLite) and reading the official MySQL documentation. I've used mysqljs but haven't really looked at its code. I've avoided reading the source code of the official connector, due to not wanting to incorporate LGPL code into this project.

**Comment by greghroberts** [comment]
Makes sense. For Travis, I've been doing things inside docker containers. I can setup a couple builds this way as it's the easiest to handle multiple versions.  Referencing the node implementation was helpful to me when I was playing around as it's MIT too and then https://github.com/npgsql/npgsql is probably another decent one for ideas around connection pooling or similar issues.

**Comment by bgrainger** [comment]
Got simple Travis (2868a09ff65cf12dae3c1d098c9d6da1f52e5e7f) and Appveyor (d5f59907399a5cb944695fe02040415e8f1aecfb) builds up, and linked to from the README.

**Comment by bgrainger** [comment]
Now also running all the integration tests (SideBySide.New) against MySQL on both Travis and Appveyor.
