### ISSUE TITLE
Consider error messages starting with 0x48

### ISSUE THREAD

**Issue by caleblloyd** [bgrainger/MySqlConnector#68]
I have hit 2 MySql error messages starting with the byte 0x48 instead of 0x23.

These exceptions are:

- 1130 Host 'x.x.x.x' is not allowed to connect to this MySql Server
- 1203 Too Many Connections

Presently the exception comes across as:

    Unhandled Exception: System.FormatException: Expected to read 0x23 but got 0x48
       at MySql.Data.ByteArrayReader.ReadByte(Byte value)

I'm working up a fix to check for 0x23 and 0x48 that will print:

    Unhandled Exception: MySql.Data.MySqlClient.MySqlException: '172.17.0.1' is not allowed to connect to this MySQL server
       at MySql.Data.Serialization.PayloadData.ThrowIfError()

**Comment by bgrainger** [comment]
Shipped in [0.1.0-alpha25](https://www.nuget.org/packages/MySqlConnector/0.1.0-alpha25).
