### ISSUE TITLE
Consider Raising the default Buffer Size or using a Buffer Pool to decrease GC

### ISSUE THREAD

**Issue by caleblloyd** [bgrainger/MySqlConnector#80]
The Performance Test's result set is ~14KB when it runs GET methods and retrieves 10 rows from the database.  Consider the following performance test setup, when the [buffer size](https://github.com/bgrainger/MySqlConnector/blob/master/src/MySqlConnector/Serialization/PacketTransmitter.cs#L15) is run with 4KiB (the default), and 64KiB.

	Rate = 1500 RPS
	Duration = 60s
	Targets = targets-async.txt

	                        mean    50%    95%    99%     max
	4KiB  Buffer Latencies  2.22s, 2.46s, 4.52s, 4.72s, 10.69s
	64KiB Buffer Latencies  0.19s, 0.08s, 0.76s, 0.86s,  6.65s

The 4KiB buffer is smaller than the packet that comes in, so a new buffer is [allocated](https://github.com/bgrainger/MySqlConnector/blob/master/src/MySqlConnector/Serialization/PacketTransmitter.cs#L206) on every request.  There is a huge slowdown due to all of the allocation and Garbage Collection that happens.

- A 64 KiB buffer size would allocate 6MiB of RAM with a connection pool of 100 connections.  This would cover pretty common use cases
- A buffer manager like [System.ServiceModel.Channels.BufferManager](https://msdn.microsoft.com/en-us/library/system.servicemodel.channels.buffermanager(v=vs.110).aspx) would be great.  Does something like this exist for .NET Core?

**Comment by bgrainger** [comment]
The 4KiB size wasn't really determined empirically; I have no objection to raising it to 64KiB.

A buffer pool could be useful if `PacketTransmitter.m_buffer` spends a lot of time "idle" (i.e., doesn't contain any extra data the client hasn't read yet).

**Comment by caleblloyd** [comment]
It looks like MySQL has a global variable called [net_buffer_length](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_net_buffer_length) that is set to 16KiB by default.

I did some testing on Wireshark, and it looks like MySQL does a good job of respecting this so long as no MySQL Packet in the Result Set exceeds this limit.  If a packet in the result set does exceed this limit, all bets are off for the rest of the Result Set and `net_buffer_length` will grow up to `max_packet_length`.

`net_buffer_length` gets reset after each SELECT statement, so worst case scenario we are allocating new buffers only for SELECT statements with large columns in their result sets.

I'll open a PR to change the default buffer size to 16KiB.  We can skip the buffer pool for now, it may be more effort than it's worth for the most common use cases.
