### ISSUE TITLE
When can we expect a non-prerelease nuget package

### ISSUE THREAD

**Issue by kwaazaar** [bgrainger/MySqlConnector#81]
My own solution uses this library, by referencing its nuget package. However, when installing my package (Resonance.Core), nuget displays an error message: Unable to resolve dependency 'MySqlConnector'. Source(s) used: 'nuget.org'. I have the 'Include prerelease'-flag set.

I know this is a nuget issue, not yours. Keep up the great work! :+

**Comment by bgrainger** [comment]
I've removed the "alpha" label and shipped [0.1.0](https://www.nuget.org/packages/MySqlConnector/0.1.0). This is still "pre-release" software and should be used with caution until "1.0" is released.

**Comment by kwaazaar** [comment]
Great, thanks!
